export const situationCrimePreventionClassificationTable = `

#### Situational Crime Prevention techniques

| Increase the effort | Increase the risks | Reduce the rewards | Reduce provocations | Remove excuses |
|---------------------|---------------------|---------------------|----------------------|-----------------|
| 1. Target harden<br>- Steering column locks and ignition immobilizers<br>- Anti-robbery screens<br>- Tamper-proof packaging | 6. Extend guardianship<br>- Go out in group at night<br>- Leave signs of occupancy<br>- Carry cell phone | 11. Conceal targets<br>- Off-street parking<br>- Gender-neutral phone directories<br>- Unmarked armored trucks | 16. Reduce frustrations and stress<br>- Efficient lines<br>- Polite service<br>- Expanded seating<br>- Soothing music/muted lights | 21. Set rules<br>- Rental agreements<br>- Harassment codes<br>- Hotel registration |
| 2. Control access to facilities<br>- Entry phones<br>- Electronic card access<br>- Baggage screening | 7. Assist natural surveillance<br>- Improved street lighting<br>- Defensible space design<br>- Support whistleblowers | 12. Remove targets<br>- Removable car radio<br>- Women's shelters<br>- Pre-paid cards for pay phones | 17. Avoid disputes<br>- Separate seating for rival soccer fans<br>- Reduce crowding in bars<br>- Fixed cab fares | 22. Post instructions<br>- "No parking"<br>- "Private property"<br>- "Extinguish camp fires" |
| 3. Screen exits<br>- Ticket needed for exit<br>- Export documents<br>- Electronic merchandise tags | 8. Reduce anonymity<br>- Taxi driver IDs<br>- "How's my driving?" decals<br>- School uniforms | 13. Identify property<br>- Property marking<br>- Vehicle licensing and parts marking<br>- Cattle branding | 18. Reduce temptation and arousal<br>- Controls on violent pornography<br>- Enforce good behavior on soccer field<br>- Prohibit racial slurs | 23. Alert conscience<br>- Roadside speed display boards<br>- Signatures for customs declarations<br>- "Shoplifting is stealing" |
| 4. Deflect offenders<br>- Street closures<br>- Separate bathrooms for women<br>- Disperse pubs | 9. Use place managers<br>- CCTV for double-deck buses<br>- Two clerks for convenience stores<br>- Reward vigilance | 14. Disrupt markets<br>- Monitor pawn shops<br>- Controls on classified ads<br>- License street vendors | 19. Neutralize peer pressure<br>- "Idiots drink and drive"<br>- "It's OK to say No"<br>- Disperse troublemakers at school | 24. Assist compliance<br>- Easy library checkout<br>- Public lavatories<br>- Litter receptacles |
| 5. Control tools/weapons<br>- "Smart" guns<br>- Restrict spray paint sales to juveniles<br>- Toughened beer glasses | 10. Strengthen formal surveillance<br>- Red light cameras<br>- Burglar alarms<br>- Security guards | 15. Deny benefits<br>- Ink merchandise tags<br>- Graffiti cleaning<br>- Disabling stolen cell phones | 20. Discourage imitation<br>- Rapid repair of vandalism<br>- V-chips in TVs<br>- Censor details of modus operandi | 25. Control drugs and alcohol<br>- Breathalyzers in bars<br>- Server intervention programs<br>- Alcohol-free events |
`;

export const situationCrimePreventionClassificationTableNL = `

#### Situational Crime Prevention technieken

| Verhoog de inspanning | Verhoog de risico's | Verminder de beloningen | Verminder provocaties | Verwijder excuses |
|------------------------|----------------------|--------------------------|-------------------------|---------------------|
| 1. Doelversteviging<br>- Stuursloten en startonderbrekers<br>- Anti-overval schermen<br>- Manipulatiebestendige verpakking | 6. Breid toezicht uit<br>- Ga 's nachts in groep uit<br>- Laat tekenen van bewoning achter<br>- Draag een mobiele telefoon | 11. Verberg doelen<br>- Parkeren buiten de straat<br>- Genderneutrale telefoongidsen<br>- Ongemarkeerde gepantserde vrachtwagens | 16. Verminder frustraties en stress<br>- Efficiënte rijen<br>- Beleefde service<br>- Uitgebreide zitplaatsen<br>- Rustgevende muziek/gedempte verlichting | 21. Stel regels op<br>- Huurovereenkomsten<br>- Intimidatiecodes<br>- Hotelregistratie |
| 2. Controleer toegang tot faciliteiten<br>- Deurtelefoons<br>- Elektronische kaart toegang<br>- Bagagecontrole | 7. Ondersteun natuurlijk toezicht<br>- Verbeterde straatverlichting<br>- Verdedigbaar ruimteontwerp<br>- Ondersteuning van klokkenluiders | 12. Verwijder doelen<br>- Verwijderbare autoradio<br>- Vrouwenopvang<br>- Prepaidkaarten voor openbare telefoons | 17. Vermijd geschillen<br>- Gescheiden zitplaatsen voor rivaliserende voetbalfans<br>- Verminder drukte in bars<br>- Vaste taxitarieven | 22. Plaats instructies<br>- "Parkeren verboden"<br>- "Privé-eigendom"<br>- "Doof kampvuren" |
| 3. Controleer uitgangen<br>- Ticket nodig voor vertrek<br>- Exportdocumenten<br>- Elektronische artikelbeveiliging | 8. Verminder anonimiteit<br>- Taxichauffeur ID's<br>- "Hoe is mijn rijgedrag?" stickers<br>- Schooluniformen | 13. Identificeer eigendom<br>- Eigendomsmarkering<br>- Voertuigregistratie en onderdelenmarkering<br>- Veemerken | 18. Verminder verleiding en opwinding<br>- Controles op gewelddadige pornografie<br>- Handhaaf goed gedrag op voetbalveld<br>- Verbied racistische opmerkingen | 23. Activeer geweten<br>- Snelheidsweergaveborden langs de weg<br>- Handtekeningen voor douaneaangiften<br>- "Winkeldiefstal is stelen" |
| 4. Leid overtreders af<br>- Straatafsluitingen<br>- Aparte toiletten voor vrouwen<br>- Verspreid pubs | 9. Gebruik plaatsmanagers<br>- CCTV voor dubbeldekkers<br>- Twee bedienden voor gemakswinkels<br>- Beloon waakzaamheid | 14. Verstoor markten<br>- Monitor pandjeshuis<br>- Controles op rubrieksadvertenties<br>- Vergunning voor straatverkopers | 19. Neutraliseer groepsdruk<br>- "Idioten drinken en rijden"<br>- "Het is OK om Nee te zeggen"<br>- Verspreid onruststokers op school | 24. Help bij naleving<br>- Eenvoudige bibliotheekuitleen<br>- Openbare toiletten<br>- Afvalbakken |
| 5. Beheers gereedschappen/wapens<br>- "Slimme" wapens<br>- Beperk verkoop spuitverf aan jongeren<br>- Geharde bierglazen | 10. Versterk formeel toezicht<br>- Roodlichtcamera's<br>- Inbraakalarm<br>- Beveiligingspersoneel | 15. Ontzeg voordelen<br>- Inktlabels op artikelen<br>- Graffiti reiniging<br>- Uitschakelen gestolen mobiele telefoons | 20. Ontmoedig imitatie<br>- Snelle reparatie van vandalisme<br>- V-chips in TV's<br>- Censureer details van modus operandi | 25. Beheers drugs en alcohol<br>- Ademanalysers in bars<br>- Interventie programma's voor barpersoneel<br>- Alcoholvrije evenementen |
`;
